#line 1 "tmpl/main_window.tmpl"
#include "main_window.h"
#line 2 "tmpl/main_window.tmpl"
namespace my_skin {
	#line 3 "tmpl/main_window.tmpl"
	struct  phoenix_view :public cppcms::base_view
	#line 3 "tmpl/main_window.tmpl"
	{
	#line 3 "tmpl/main_window.tmpl"
		main_window_content::content &content;
	#line 3 "tmpl/main_window.tmpl"
		phoenix_view(std::ostream &_s,main_window_content::content &_content): cppcms::base_view(_s),content(_content),_domain_id(0)
	#line 3 "tmpl/main_window.tmpl"
		{
	#line 3 "tmpl/main_window.tmpl"
			_domain_id=booster::locale::ios_info::get(_s).domain_id();
	#line 3 "tmpl/main_window.tmpl"
		}
		#line 4 "tmpl/main_window.tmpl"
		virtual void render() {
		#line 4 "tmpl/main_window.tmpl"
			cppcms::translation_domain_scope _trs(out(),_domain_id);

			#line 12 "tmpl/main_window.tmpl"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html lang=\"en\">\n"
				"\n"
				"<head>\n"
				"  <meta charset=\"utf-8\">\n"
				"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
				"  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n"
				"  <title>";
			#line 12 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.title);
			#line 51 "tmpl/main_window.tmpl"
			out()<<"</title>\n"
				"  <!-- Font Awesome -->\n"
				"  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\n"
				"  <!-- Bootstrap core CSS -->\n"
				"  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Material Design Bootstrap -->\n"
				"  <link href=\"css/mdb.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Your custom styles (optional) -->\n"
				"  <link href=\"css/style.css\" rel=\"stylesheet\">\n"
				"</head>\n"
				"<style>\n"
				"  main{\n"
				"    font-family: Arial, \"Times New Roman\", sans-serif;\n"
				"\n"
				"    height: 100vh;\n"
				"    background-image: linear-gradient(to bottom, #fbbe4b, #f3b540, #ecab35, #e4a229, #dc991b);\n"
				"  }\n"
				"  \n"
				"  \n"
				"</style>\n"
				"<body>\n"
				"  <main>\n"
				"    <header> \n"
				"      <nav class=\"navbar navbar-expand-lg navbar-dark orange accent-4\">\n"
				"        <div class=\"container-fluid\">\n"
				"          <a href=\"#\" class=\"navbar-brand waves-effect\"><strong class=\"\" style=\"font-size: 25px\">PHOENIX</strong></a>   \n"
				"\n"
				"          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n"
				"          aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				"          <span class=\"navbar-toggler-icon\"></span>\n"
				"           </button>   \n"
				"        <div class=\"navbar-collapse collapse\" id=\"navbarNav\">\n"
				"          <ul class=\"navbar-nav mr-auto\">\n"
				"            <li class=\"nav-item active\"><a href=\"#\" class=\"nav-link\">test<span class=\"sr-only\">(current)</span></a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test2</a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test3</a></li>\n"
				"          </ul>\n"
				"          <form method=\"POST\" class=\"form-inline\">\n"
				"            <div class=\"md-form my-0\">\n"
				"              <input autocomplete=\"off\" type=\"search\" class=\"form-control mr-sm-2\" name=\"input1\" placeholder=\"";
			#line 51 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.search.placeholder);
			#line 54 "tmpl/main_window.tmpl"
			out()<<"\" aria-label=\"Search\">\n"
				"              \n"
				"            </div>\n"
				"            <button class=\"btn btn-outline-white btn-md ml-2\" type=\"submit\" >";
			#line 54 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.search.button_name);
			#line 59 "tmpl/main_window.tmpl"
			out()<<"</button>\n"
				"          </form>\n"
				"          <div class=\"dropdown\">\n"
				"            <button class=\"m-0 ml-2 btn peach-gradient dropdown-toggle pb-2 pr-3 pl-3 pt-2\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"  style=\"border-radius: 8px\">\n"
				"              <img src=\"img/question.jpeg\" style=\"width:30px; height: 30px;\"alt=\"\" class=\"img rounded-circle m-0 p-0\">\n"
				"              ";
			#line 59 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.account.account_name);
			#line 154 "tmpl/main_window.tmpl"
			out()<<"\n"
				"            </button>\n"
				"            <div class=\"dropdown-menu\">\n"
				"              <a href=\"#\" class=\"dropdown-item\" onclick=\"$('#main_card').toggle()\">Account</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Settings</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Notes</a>\n"
				"              <div class=\"dropdown-divider\"></div>\n"
				"              <a href=\"#\" class=\"dropdown-item text-right\">Exit</a>\n"
				"            </div>\n"
				"          </div>\n"
				"        </div> \n"
				"        </div>\n"
				"      </nav>\n"
				"    </header>\n"
				"\n"
				"    \n"
				"    <style>\n"
				"      #main_card{\n"
				"        position:  absolute;\n"
				"        width: 600px;\n"
				"        height: 550px;\n"
				"        margin-left: 35vw;\n"
				"        margin-top: 10vh;\n"
				"      }\n"
				"    </style>\n"
				"\n"
				"    <div class=\"card rounded-bottom\"  id=\"main_card\" style=\"display:none; z-index: 3;\">\n"
				"        \n"
				"        <div class=\"card-body amber lighten-5\">\n"
				"          \n"
				"          <ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\n"
				"            <li class=\"nav-item\">\n"
				"              <a class=\"nav-link active\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">Registration</a>\n"
				"            </li>\n"
				"            <li class=\"nav-item\">\n"
				"            <a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">Login</a>\n"
				"            </li>\n"
				"\n"
				"          </ul>\n"
				"          <div class=\"tab-content\" id=\"myTabContent\">\n"
				"            <div class=\"mb-0 mt-1\" style=\"display: none; \" id=\"reg_error\"><p style=\"color:red\"></p></div>\n"
				"            <div class=\"tab-pane fade show active pt-2\" id=\"home\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\n"
				"              <p>Input your name:</p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas fa-user prefix\"></i>\n"
				"                <input name=\"Login\" type=\"text\" id=\"inputText1\" class=\"form-control\" autofocus=\"true\">\n"
				"                <label for=\"inputText1\">Login</label>\n"
				"              </div>\n"
				"              <p>Input your email:</p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas fa-envelope prefix\"></i>\n"
				"                <input type=\"email\" name=\"Email\" id=\"inputText2\" class=\"form-control\">\n"
				"                <label for=\"inputText2\">Email</label>\n"
				"              </div>\n"
				"              <p>Input password:  </p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas prefix fa-key\"></i>\n"
				"                <input type=\"password\" name=\"password_1\" id=\"inputText3\" class=\"form-control\">\n"
				"                <label for=\"inputText3\">Password</label>\n"
				"              </div>\n"
				"              <p>Input password again:</p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas prefix fa-key\"></i>\n"
				"                <input type=\"password\" name=\"password_2\" id=\"inputText4\" class=\"form-control\">\n"
				"                <label for=\"inputText4\">Password</label>\n"
				"              </div>\n"
				"              <div style=\"text-align: center;\"><button class=\"btn btn-primary\" type=\"button\" onclick=\"createuser($('#inputText1').val(),$('#inputText2').val(), $('#inputText3').val(),$('#inputText4').val() )\">REG</button></div>\n"
				"            </div>\n"
				"            <div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\" aria-labelledby=\"profile-tab\"> \n"
				"              <p>Input your name or email:</p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas fa-user prefix\"></i>\n"
				"                <input name=\"Login\" type=\"text\" id=\"inputText5\" class=\"form-control\">\n"
				"                <label for=\"inputText5\">Login or email</label>\n"
				"              </div>\n"
				"              <p>Input password:</p>\n"
				"              <div class=\"md-form mt-0\">\n"
				"                <i class=\"fas prefix fa-key\"></i>\n"
				"                <input type=\"password\" name=\"password_1\" id=\"inputText6\" class=\"form-control\">\n"
				"                <label for=\"inputText6\">Password</label>\n"
				"              </div>\n"
				"              <div style=\"text-align: center;\"><button class=\"btn btn-primary\" type=\"button\" onclick=\"loginuser($('#inputText5').val(),$('#inputText6').val())\">LOGIN</button></div>\n"
				"            </div>\n"
				"          </div>\n"
				"        </div>\n"
				"      </div>\n"
				"\n"
				"\n"
				"\n"
				"    <div class=\"pt-2 mt-2\">\n"
				"      <div class=\"container-fluid\">\n"
				"        <div class=\"row\">\n"
				"          <div class=\"col-md-9 \">\n"
				"            <div class=\"card waves-effect animated fadeInDown faster\">\n"
				"              <div class=\"card-body\">\n"
				"                <h3 class=\"card-title\" style=\"text-align: left;\">";
			#line 154 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.hello_user_text);
			#line 156 "tmpl/main_window.tmpl"
			out()<<"</h3>\n"
				"                <p class=\"\" style=\"font-size: 17px;\">\n"
				"                  ";
			#line 156 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.welcome_text);
			#line 158 "tmpl/main_window.tmpl"
			out()<<"\n"
				"                </p>\n"
				"                <a class=\"btn btn-primary mt-0\" href=\"#\" onclick=\"$('#main_card').show()\">";
			#line 158 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.reg_button_name);
			#line 165 "tmpl/main_window.tmpl"
			out()<<"</a>\n"
				"              </div>\n"
				"            </div>\n"
				"            <div class=\"row\">\n"
				"              <div class=\"col-md-4\">\n"
				"                <div class=\"card waves-effect mt-4 animated fadeInLeft faster\">\n"
				"                  <div class=\"card-body\">\n"
				"                    <h3 class=\"card-title text-left\">";
			#line 165 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.new_text_title);
			#line 167 "tmpl/main_window.tmpl"
			out()<<"</h3>\n"
				"                    <p>\n"
				"                      ";
			#line 167 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.new_text);
			#line 175 "tmpl/main_window.tmpl"
			out()<<"\n"
				"                    </p>\n"
				"                  </div>\n"
				"                </div>\n"
				"              </div>\n"
				"              <div class=\"col-md-8\">\n"
				"                <div class=\"card waves-effect mt-4 animated fadeInUp fast\">\n"
				"                  <div class=\"card-body\">\n"
				"                    <h3 class=\"card-title text-left\">";
			#line 175 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.examples.title);
			#line 180 "tmpl/main_window.tmpl"
			out()<<"</h3>\n"
				"                    <div class=\"example-image\">\n"
				"                      <div class=\"row\">\n"
				"                        <div class=\"col-md-4\">\n"
				"                          <div class=\"card waves-effect\">\n"
				"                            <h5 class=\"\">";
			#line 180 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.examples.names.at(0));
			#line 185 "tmpl/main_window.tmpl"
			out()<<"</h5>\n"
				"                          </div>\n"
				"                        </div>\n"
				"                        <div class=\"col-md-4\">\n"
				"                          <div class=\"card waves-effect\">\n"
				"                            <h5 class=\"\">";
			#line 185 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.examples.names.at(1));
			#line 190 "tmpl/main_window.tmpl"
			out()<<"</h5>\n"
				"                          </div>\n"
				"                        </div>\n"
				"                        <div class=\"col-md-4\">\n"
				"                          <div class=\"card waves-effect\">\n"
				"                            <h5 class=\"\">";
			#line 190 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.examples.names.at(2));
			#line 203 "tmpl/main_window.tmpl"
			out()<<"</h5>\n"
				"                          </div>\n"
				"                        </div>\n"
				"                      </div>\n"
				"                    </div>\n"
				"                  </div>\n"
				"                </div>\n"
				"              </div>\n"
				"            </div>\n"
				"          </div>\n"
				"          <div class=\"col-md-3 animated fadeInRight faster\">\n"
				"            <div class=\"card waves-effect\">\n"
				"              <div class=\"card-body\">\n"
				"                <h3 class=\"card-title text-center\">";
			#line 203 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.quick_note.title);
			#line 206 "tmpl/main_window.tmpl"
			out()<<"</h3>\n"
				"                <hr class=\"my-2\">\n"
				"                <div class=\"form-group shadow-textarea\">\n"
				"                  <label for=\"QuickNoteTextArea\">";
			#line 206 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.quick_note.input_text);
			#line 207 "tmpl/main_window.tmpl"
			out()<<"</label>\n"
				"                  <textarea style=\"max-height: 65vh\" name=\"";
			#line 207 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.qn_form.textarea.name());
			#line 209 "tmpl/main_window.tmpl"
			out()<<"\"  id=\"QuickNoteTextArea\" cols=\"30\" rows=\"10\" class=\"form-control z-depth-1\" placeholder=\"Write Something...\" spellcheck=\"false\"></textarea>\n"
				"                </div>\n"
				"                <div class=\"text-center\"><button class=\"btn btn-danger\" onclick=\"create_quick_note($('#QuickNoteTextArea').val())\">";
			#line 209 "tmpl/main_window.tmpl"
			out()<<cppcms::filters::escape(content.quick_note.button_name);
			#line 346 "tmpl/main_window.tmpl"
			out()<<"</button></div>\n"
				"              </div>\n"
				"              </div>\n"
				"            </div>\n"
				"          </div>\n"
				"        </div>\n"
				"      </div>\n"
				"    </div>\n"
				"\n"
				"\n"
				"\n"
				"  </main>\n"
				"\n"
				"\n"
				"  <!-- SCRIPTS -->\n"
				"  <!-- AutoSize TextArea -->\n"
				"  <script src=\"https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js\"></script>\n"
				"  <script>\n"
				"    autosize(document.getElementById('QuickNoteTextArea'));\n"
				"  </script>\n"
				"  <!-- JQuery -->\n"
				"  <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\n"
				"  <!-- Bootstrap tooltips -->\n"
				"  <script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\n"
				"  <!-- Bootstrap core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n"
				"  <!-- MDB core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/mdb.min.js\"></script>\n"
				"  <!-- Для мувов -->\n"
				"  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js\"></script>    \n"
				"  <script>\n"
				"    $(\"#main_card\").draggable();\n"
				"\n"
				"\n"
				"    jQuery(function($){\n"
				"  $(document).mouseup(function (e){ // событие клика по веб-документу\n"
				"    var div = $(\"#main_card\"); // тут указываем ID элемента\n"
				"    if (!div.is(e.target) // если клик был не по нашему блоку\n"
				"        && div.has(e.target).length === 0) { // и не по его дочерним элементам\n"
				"      div.hide(); // скрываем его\n"
				"    }\n"
				"  });\n"
				"});\n"
				"  </script>\n"
				"  <script>\n"
				"    function createuser(name,email,pass,pass2) {\n"
				"      if (name =='' ||  email=='' || pass=='' || pass!=pass2 || pass.length <=5) { // а также ещё куча условий\n"
				"        if (name==''){\n"
				"          $(\"#reg_error > p\").text(\"Please input name\");\n"
				"        }\n"
				"        else if (email==''){\n"
				"          $(\"#reg_error > p\").text(\"Please input email\");\n"
				"        }\n"
				"        else if (pass==''){\n"
				"          $(\"#reg_error > p\").text(\"Please input password\");\n"
				"        }\n"
				"        else if(pass !=pass2){\n"
				"          $(\"#reg_error > p\").text(\"Password 1 != password 2\");\n"
				"        }\n"
				"        else if(pass.length <=5){\n"
				"          $(\"#reg_error > p\").text(\"Password is very short (<=5)\");\n"
				"        }\n"
				"        $(\"#reg_error\").show();\n"
				"      }\n"
				"      else{\n"
				"        res = jQuery.post(\"http://phoenixnote.site/post/create_user\",{name:name,email:email,pass:pass},function(data){\n"
				"          if (res.responseText == \"user with this name exist\" || res.responseText == \"user with this email exist\"){\n"
				"            $(\"#reg_error > p\").text(res.responseText);\n"
				"            $(\"#reg_error\").show();\n"
				"          }\n"
				"          else{\n"
				"            $(\"#reg_error > p\").text('created');\n"
				"            $(\"#reg_error\").show();\n"
				"          }  \n"
				"        },);\n"
				"\n"
				"\n"
				"        \n"
				"\n"
				"      }\n"
				"    }\n"
				"\n"
				"    function loginuser(name,pass) {\n"
				"      if(name=='' || pass==''){\n"
				"        if (name==''){\n"
				"          $(\"#reg_error > p\").text(\"Please input name or email\");\n"
				"          $(\"#reg_error\").show();\n"
				"        }\n"
				"        else if (pass == ''){\n"
				"          $(\"#reg_error > p\").text(\"Please input password\");\n"
				"          $(\"#reg_error\").show();\n"
				"        }\n"
				"      }\n"
				"      else{\n"
				"        res = $.post('http://phoenixnote.site/post/login_user', {\"login\": name, \"pass\":pass}, function(data) {\n"
				"          /*optional stuff to do after success */\n"
				"          //проверка на то, что логин прошел успешно:\n"
				"          if(data == \"user with this name or email not exist\" || data == \"WRONG PASSWORD\"){\n"
				"            $(\"#reg_error > p\").text(data); \n"
				"            $(\"#reg_error\").show();\n"
				"          }\n"
				"          else{\n"
				"            //запрос на создание сессии\n"
				"            $.post('http://phoenixnote.site/post/create_user_session', {\"user_id\": data}, function(data2) {\n"
				"              /*optional stuff to do after success */\n"
				"              if(data2 == \"success\"){\n"
				"                window.location.assign(\"http://phoenixnote.site/user\");\n"
				"              }\n"
				"              else{\n"
				"                $(\"#reg_error > p\").text(\"problmes with session\");\n"
				"                $(\"#reg_error\").show();\n"
				"              }\n"
				"            });\n"
				"          }\n"
				"        });\n"
				"      }\n"
				"    }\n"
				"\n"
				"\n"
				"    function create_quick_note(text){\n"
				"      if (text == ''){\n"
				"        $(\"#QuickNoteTextArea\").val(\"please input text\");\n"
				"      }\n"
				"      else{\n"
				"        $.post(\"http://phoenixnote.site/post/create_quick_note\",{\"text\":text,date:\"2019-05-05 5:12\"}, function(data){\n"
				"          window.location.assign(\"http://phoenixnote.site/note_page?note=\"+data);\n"
				"        }); \n"
				"        //window.location.replace(\"http://phoenixnote.site/note_page?note=\"+ans.responseText);\n"
				"        \n"
				"\n"
				"      }\n"
				"    }\n"
				"  </script>\n"
				"</body>\n"
				"\n"
				"</html>\n"
				"\n"
				"";
		#line 346 "tmpl/main_window.tmpl"
		} // end of template render
	#line 348 "tmpl/main_window.tmpl"
	private:
	#line 348 "tmpl/main_window.tmpl"
		int _domain_id;
	#line 348 "tmpl/main_window.tmpl"
	}; // end of class phoenix_view
#line 349 "tmpl/main_window.tmpl"
} // end of namespace my_skin
#line 2 "tmpl/main_window.tmpl"
namespace my_skin {
#line 349 "tmpl/main_window.tmpl"
} // end of namespace my_skin
#line 349 "tmpl/main_window.tmpl"
namespace {
#line 349 "tmpl/main_window.tmpl"
 cppcms::views::generator my_generator; 
#line 349 "tmpl/main_window.tmpl"
 struct loader { 
#line 349 "tmpl/main_window.tmpl"
  loader() { 
#line 349 "tmpl/main_window.tmpl"
   my_generator.name("my_skin");
#line 349 "tmpl/main_window.tmpl"
   my_generator.add_view<my_skin::phoenix_view,main_window_content::content>("phoenix_view",true);
#line 349 "tmpl/main_window.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 349 "tmpl/main_window.tmpl"
 }
#line 349 "tmpl/main_window.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 349 "tmpl/main_window.tmpl"
} a_loader;
#line 349 "tmpl/main_window.tmpl"
} // anon 
