#line 1 "tmpl/note_page.tmpl"
#include "note_page.h"
#line 2 "tmpl/note_page.tmpl"
namespace my_skin {
	#line 3 "tmpl/note_page.tmpl"
	struct  note_page_view :public cppcms::base_view
	#line 3 "tmpl/note_page.tmpl"
	{
	#line 3 "tmpl/note_page.tmpl"
		note_page_content::content &content;
	#line 3 "tmpl/note_page.tmpl"
		note_page_view(std::ostream &_s,note_page_content::content &_content): cppcms::base_view(_s),content(_content),_domain_id(0)
	#line 3 "tmpl/note_page.tmpl"
		{
	#line 3 "tmpl/note_page.tmpl"
			_domain_id=booster::locale::ios_info::get(_s).domain_id();
	#line 3 "tmpl/note_page.tmpl"
		}
		#line 4 "tmpl/note_page.tmpl"
		virtual void render() {
		#line 4 "tmpl/note_page.tmpl"
			cppcms::translation_domain_scope _trs(out(),_domain_id);

			#line 59 "tmpl/note_page.tmpl"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html lang=\"en\">\n"
				"\n"
				"<head>\n"
				"  <meta charset=\"utf-8\">\n"
				"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
				"  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n"
				"  <title>PHOENIX</title>\n"
				"  <!-- Font Awesome -->\n"
				"  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\n"
				"  <!-- Bootstrap core CSS -->\n"
				"  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Material Design Bootstrap -->\n"
				"  <link href=\"css/mdb.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Your custom styles (optional) -->\n"
				"  <link href=\"css/style.css\" rel=\"stylesheet\">\n"
				"</head>\n"
				"<style>\n"
				"  main{\n"
				"    font-family: Arial, \"Times New Roman\", sans-serif;\n"
				"\n"
				"    height: 100vh;\n"
				"    background-image: linear-gradient(to bottom, #fbbe4b, #f3b540, #ecab35, #e4a229, #dc991b);\n"
				"  }\n"
				"  \n"
				"  \n"
				"</style>\n"
				"<body>\n"
				"  <main>\n"
				"    <header> \n"
				"      <nav class=\"navbar navbar-expand-lg navbar-dark orange accent-4\">\n"
				"        <div class=\"container-fluid\">\n"
				"          <a href=\"#\" class=\"navbar-brand waves-effect\"><strong class=\"\" style=\"font-size: 25px\">PHOENIX</strong></a>   \n"
				"\n"
				"          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n"
				"          aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				"          <span class=\"navbar-toggler-icon\"></span>\n"
				"           </button>   \n"
				"        <div class=\"navbar-collapse collapse\" id=\"navbarNav\">\n"
				"          <ul class=\"navbar-nav mr-auto\">\n"
				"            <li class=\"nav-item active\"><a href=\"#\" class=\"nav-link\">test<span class=\"sr-only\">(current)</span></a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test2</a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test3</a></li>\n"
				"          </ul>\n"
				"          <form method=\"POST\" class=\"form-inline\">\n"
				"            <div class=\"md-form my-0\">\n"
				"              <input autocomplete=\"off\" type=\"search\" class=\"form-control mr-sm-2\" name=\"input1\" placeholder=\"Search\" aria-label=\"Search\">\n"
				"              \n"
				"            </div>\n"
				"            <button class=\"btn btn-outline-white btn-md ml-2\" type=\"submit\" >Search</button>\n"
				"          </form>\n"
				"          <div class=\"dropdown\">\n"
				"            <button class=\"m-0 ml-2 btn peach-gradient dropdown-toggle pb-2 pr-3 pl-3 pt-2\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"  style=\"border-radius: 8px\">\n"
				"              <img src=\"img/question.jpeg\" style=\"width:30px; height: 30px;\"alt=\"\" class=\"img rounded-circle m-0 p-0\">\n"
				"              ";
			#line 59 "tmpl/note_page.tmpl"
			out()<<cppcms::filters::escape(content.account.account_name);
			#line 96 "tmpl/note_page.tmpl"
			out()<<"\n"
				"            </button>\n"
				"            <div class=\"dropdown-menu\">\n"
				"              <a href=\"#\" class=\"dropdown-item\" onclick=\"$('#main_card').toggle()\">Account</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Settings</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Notes</a>\n"
				"              <div class=\"dropdown-divider\"></div>\n"
				"              <a href=\"#\" class=\"dropdown-item text-right\">Exit</a>\n"
				"            </div>\n"
				"          </div>\n"
				"        </div> \n"
				"        </div>\n"
				"      </nav>\n"
				"    </header>\n"
				"\n"
				"    <style>\n"
				"      .mycard{\n"
				"        position:  absolute;\n"
				"        left: 40%;\n"
				"        top: 20%;\n"
				"        height: 30%;\n"
				"        width: 20%;\n"
				"        border-radius: 9px;\n"
				"      }\n"
				"      .main_textarea{\n"
				"        width: 100%;\n"
				"        height: 100%;\n"
				"        min-height: 100%;\n"
				"        max-height: 100%;\n"
				"        resize: none;\n"
				"      }\n"
				"    </style>\n"
				"\n"
				"    \n"
				"    <div class=\"card mycard\" id=\"main_card\">\n"
				"      <div class=\"card-body\" >\n"
				"        <div class=\"card-title\" style=\"text-align: center;\">\n"
				"          <h3 id=\"local_id\">";
			#line 96 "tmpl/note_page.tmpl"
			out()<<cppcms::filters::escape(content.local_id);
			#line 99 "tmpl/note_page.tmpl"
			out()<<"</h3>\n"
				"        </div>\n"
				"        <div class=\"container-fluid m-0  p-0 pb-5\" style=\"height: 100%\">\n"
				"          <textarea   style =\"resize:none; height: 100%;\"name=\"test\"  id=\"QuickNoteTextArea\"  class=\"form-control z-depth-1\" placeholder=\"Write Something...\" spellcheck=\"false\" id=\"main_textarea\" >";
			#line 99 "tmpl/note_page.tmpl"
			out()<<cppcms::filters::escape(content.text);
			#line 161 "tmpl/note_page.tmpl"
			out()<<"</textarea>\n"
				"        </div>\n"
				"      </div>\n"
				"    </div>\n"
				"\n"
				"    \n"
				"\n"
				"\n"
				"  </main>\n"
				"\n"
				"\n"
				"  <!-- SCRIPTS -->\n"
				"  <!-- AutoSize TextArea -->\n"
				"\n"
				"  <!-- JQuery -->\n"
				"  <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\n"
				"  <!-- Bootstrap tooltips -->\n"
				"  <script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\n"
				"  <!-- Bootstrap core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n"
				"  <!-- MDB core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/mdb.min.js\"></script>\n"
				"  <!-- Для мувов -->\n"
				"  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js\"></script>    \n"
				"  <!-- animation: -->\n"
				"  <script>\n"
				"    function update_note(local_id,new_text) {\n"
				"      // body...\n"
				"      $.post(\"http://phoenixnote.site/post/update_quick_note\",{\"local_id\":local_id,\"text\":new_text},function (data) {\n"
				"        // body...\n"
				"        //alert(data);\n"
				"      })\n"
				"    }\n"
				"\n"
				"\n"
				"    jQuery(document).ready(function($) {\n"
				"      $(\"#main_card\").animate({\n"
				"        left: \"10%\",\n"
				"        top:\"15%\",\n"
				"        height: \"70%\",\n"
				"        width: \"80%\"});\n"
				"    });\n"
				"    counter = 0;\n"
				"    jQuery(document).ready(function($) {\n"
				"      $(\"#main_card\").on('input', function(event) {\n"
				"        event.preventDefault();\n"
				"        counter +=1;\n"
				"        if (counter == 5){\n"
				"          update_note($(\"#local_id\").text() ,$(\"#QuickNoteTextArea\").val());\n"
				"          counter = 0;\n"
				"        }\n"
				"        \n"
				"        /* Act on the event */\n"
				"      });\n"
				"    });\n"
				"  </script>\n"
				"</body>\n"
				"\n"
				"</html>\n"
				"\n"
				"\n"
				"\n"
				"";
		#line 161 "tmpl/note_page.tmpl"
		} // end of template render
	#line 162 "tmpl/note_page.tmpl"
	private:
	#line 162 "tmpl/note_page.tmpl"
		int _domain_id;
	#line 162 "tmpl/note_page.tmpl"
	}; // end of class note_page_view
#line 163 "tmpl/note_page.tmpl"
} // end of namespace my_skin
#line 2 "tmpl/note_page.tmpl"
namespace my_skin {
#line 163 "tmpl/note_page.tmpl"
} // end of namespace my_skin
#line 163 "tmpl/note_page.tmpl"
namespace {
#line 163 "tmpl/note_page.tmpl"
 cppcms::views::generator my_generator; 
#line 163 "tmpl/note_page.tmpl"
 struct loader { 
#line 163 "tmpl/note_page.tmpl"
  loader() { 
#line 163 "tmpl/note_page.tmpl"
   my_generator.name("my_skin");
#line 163 "tmpl/note_page.tmpl"
   my_generator.add_view<my_skin::note_page_view,note_page_content::content>("note_page_view",true);
#line 163 "tmpl/note_page.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 163 "tmpl/note_page.tmpl"
 }
#line 163 "tmpl/note_page.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 163 "tmpl/note_page.tmpl"
} a_loader;
#line 163 "tmpl/note_page.tmpl"
} // anon 
