#line 1 "user.tmpl"
#include "user.h"
#line 2 "user.tmpl"
namespace my_skin {
	#line 3 "user.tmpl"
	struct  user_view :public cppcms::base_view
	#line 3 "user.tmpl"
	{
	#line 3 "user.tmpl"
		user_content::content &content;
	#line 3 "user.tmpl"
		user_view(std::ostream &_s,user_content::content &_content): cppcms::base_view(_s),content(_content),_domain_id(0)
	#line 3 "user.tmpl"
		{
	#line 3 "user.tmpl"
			_domain_id=booster::locale::ios_info::get(_s).domain_id();
	#line 3 "user.tmpl"
		}
		#line 4 "user.tmpl"
		virtual void render() {
		#line 4 "user.tmpl"
			cppcms::translation_domain_scope _trs(out(),_domain_id);

			#line 76 "user.tmpl"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html lang=\"en\">\n"
				"\n"
				"<head>\n"
				"  <meta charset=\"utf-8\">\n"
				"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
				"  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n"
				"  <title>PHOENIX</title>\n"
				"  <!-- Font Awesome -->\n"
				"  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\">\n"
				"  <!-- Bootstrap core CSS -->\n"
				"  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Material Design Bootstrap -->\n"
				"  <link href=\"css/mdb.min.css\" rel=\"stylesheet\">\n"
				"  <!-- Your custom styles (optional) -->\n"
				"  <link href=\"css/style.css\" rel=\"stylesheet\">\n"
				"</head>\n"
				"<style>\n"
				"  main{\n"
				"    font-family: Arial, \"Times New Roman\", sans-serif;\n"
				"\n"
				"    height: 100vh;\n"
				"    background-image: linear-gradient(to bottom, #fbbe4b, #f3b540, #ecab35, #e4a229, #dc991b);\n"
				"  }\n"
				"  .note_card{\n"
				"        height: 25vh;\n"
				"        border-radius: 5px;\n"
				"    }\n"
				"  .plus_button{\n"
				"    height: 25vh;\n"
				"    background-colour: red;\n"
				"  }\n"
				"  .create_note_card{\n"
				"    position: fixed;\n"
				"    left: 40%;\n"
				"    top: 20%;\n"
				"    height: 30%;\n"
				"    width: 20%;\n"
				"    border-radius: 9px;\n"
				"    z-index: 999;\n"
				"  }\n"
				"  \n"
				"  \n"
				"</style>\n"
				"<body>\n"
				"  <main>\n"
				"    <header> \n"
				"      <nav class=\"navbar navbar-expand-lg navbar-dark orange accent-4\">\n"
				"        <div class=\"container-fluid\">\n"
				"          <a href=\"#\" class=\"navbar-brand waves-effect\"><strong class=\"\" style=\"font-size: 25px\">PHOENIX</strong></a>   \n"
				"\n"
				"          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\"\n"
				"          aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
				"          <span class=\"navbar-toggler-icon\"></span>\n"
				"           </button>   \n"
				"        <div class=\"navbar-collapse collapse\" id=\"navbarNav\">\n"
				"          <ul class=\"navbar-nav mr-auto\">\n"
				"            <li class=\"nav-item active\"><a href=\"#\" class=\"nav-link\">test<span class=\"sr-only\">(current)</span></a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test2</a></li>\n"
				"            <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">test3</a></li>\n"
				"          </ul>\n"
				"          <form method=\"POST\" class=\"form-inline\">\n"
				"            <div class=\"md-form my-0\">\n"
				"              <input autocomplete=\"off\" type=\"search\" class=\"form-control mr-sm-2\" name=\"input1\" placeholder=\"Search\" aria-label=\"Search\">\n"
				"              \n"
				"            </div>\n"
				"            <button class=\"btn btn-outline-white btn-md ml-2\" type=\"submit\" >Search</button>\n"
				"          </form>\n"
				"          <div class=\"dropdown\">\n"
				"            <button class=\"m-0 ml-2 btn peach-gradient dropdown-toggle pb-2 pr-3 pl-3 pt-2\" type=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"  style=\"border-radius: 8px\">\n"
				"              <img src=\"img/question.jpeg\" style=\"width:30px; height: 30px;\"alt=\"\" class=\"img rounded-circle m-0 p-0\">\n"
				"              ";
			#line 76 "user.tmpl"
			out()<<cppcms::filters::escape(content.account.account_name);
			#line 155 "user.tmpl"
			out()<<"\n"
				"            </button>\n"
				"            <div class=\"dropdown-menu\">\n"
				"              <a href=\"#\" class=\"dropdown-item\" onclick=\"$('#main_card').toggle()\">Account</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Settings</a>\n"
				"              <a href=\"#\" class=\"dropdown-item\">Notes</a>\n"
				"              <div class=\"dropdown-divider\"></div>\n"
				"              <a href=\"#\" class=\"dropdown-item text-right\">Exit</a>\n"
				"            </div>\n"
				"          </div>\n"
				"        </div> \n"
				"        </div>\n"
				"      </nav>\n"
				"    </header>\n"
				"\n"
				"      <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\n"
				"\n"
				"    <!--v-bind:onclick=\"bind_click(note.id)\" -->\n"
				"    <div class=\"container-fluid main\" id=\"main\">\n"
				"\n"
				"        <div class=\"create_note_card\" id=\"create_note_card\" >\n"
				"          <div class=\"card amber lighten-5\" style=\"height: 100%; width: 100%;\">\n"
				"            <div class=\"card-body\">\n"
				"              <div class=\"card-title\" style=\"text-align:center\"><h3>Create New Note<img onclick=\"$('#create_note_card').hide();note_open = false;\" style=\"float:right; height: 20px; width: 20px;\" src=\"krest.png\"></img></h3></div>\n"
				"              <div class=\"container-fluid m-0  p-0 pb-5\" style=\"height: 100%\">\n"
				"                <textarea   style =\"resize:none; height: 100%;\"name=\"create_card_textarea\"  id=\"CreateNoteTextArea\"  class=\"form-control z-depth-1\" placeholder=\"Write Something...\" spellcheck=\"false\"></textarea>\n"
				"              </div>\n"
				"              <div style=\"text-align:center\" class=\"p-0\">\n"
				"                <button class=\"btn btn-danger\" onclick=\"create_note($('#CreateNoteTextArea').val())\">CREATE NOTE</button>\n"
				"              </div>             \n"
				"            </div>\n"
				"          </div>\n"
				"        </div>\n"
				"\n"
				"        <div class=\"row\"> \n"
				"            <div v-for=\"note in notes\" class=\"col-md-3\" >\n"
				"                <div class=\"card note_card mt-4\" v-bind:id=\"note.id\" v-bind:onclick=\"bind_click(note.id)\" >\n"
				"                    <div class=\"card-body\">\n"
				"                        <div class=\"card-title\" style=\"text-align:center\"><h3>{{note.id}} <img  v-bind:onclick=\"bind_close(note.id)\" style=\"float:right; height: 20px; width: 20px;display:none;\" src=\"krest.png\"></img></h3></div>\n"
				"                        <div class=\"container-fluid m-0 p-0 pb-5\" style=\"height: 100%\"><textarea   style =\"resize:none; height: 100%;\"   class=\"form-control z-depth-1\" placeholder=\"Write Something...\" spellcheck=\"false\">{{note.text}}</textarea></div>\n"
				"                    </div>\n"
				"                </div>\n"
				"            </div>\n"
				"            <div class=\"plus_button mt-4 col-md-3\">\n"
				"              <div class=\"picture\">\n"
				"                <img style=\"position: relative;height: 200px; width: 200; left:25%;margin-top:5%;\" src=\"plus_PNG106.png\" onclick=\"open_create_note_function()\"></img>                \n"
				"              </div>\n"
				"            </div>\n"
				"        </div>\n"
				"    </div>\n"
				"    \n"
				"\n"
				"\n"
				"\n"
				"  </main>\n"
				"\n"
				"\n"
				"  <!-- SCRIPTS -->\n"
				"\n"
				"  <!-- JQuery -->\n"
				"  <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script>\n"
				"  <!-- Bootstrap tooltips -->\n"
				"  <script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\n"
				"  <!-- Bootstrap core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n"
				"  <!-- MDB core JavaScript -->\n"
				"  <script type=\"text/javascript\" src=\"js/mdb.min.js\"></script>\n"
				"  <!-- Для мувов -->\n"
				"  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js\"></script>    \n"
				"  <!-- VUE: -->\n"
				"  <script src=\"https://cdn.jsdelivr.net/npm/vue\"></script>\n"
				"\n"
				"\n"
				"  <script src=\"user.js\"></script>\n"
				"\n"
				"</body>\n"
				"\n"
				"</html>\n"
				"\n"
				"";
		#line 155 "user.tmpl"
		} // end of template render
	#line 157 "user.tmpl"
	private:
	#line 157 "user.tmpl"
		int _domain_id;
	#line 157 "user.tmpl"
	}; // end of class user_view
#line 158 "user.tmpl"
} // end of namespace my_skin
#line 2 "user.tmpl"
namespace my_skin {
#line 158 "user.tmpl"
} // end of namespace my_skin
#line 158 "user.tmpl"
namespace {
#line 158 "user.tmpl"
 cppcms::views::generator my_generator; 
#line 158 "user.tmpl"
 struct loader { 
#line 158 "user.tmpl"
  loader() { 
#line 158 "user.tmpl"
   my_generator.name("my_skin");
#line 158 "user.tmpl"
   my_generator.add_view<my_skin::user_view,user_content::content>("user_view",true);
#line 158 "user.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 158 "user.tmpl"
 }
#line 158 "user.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 158 "user.tmpl"
} a_loader;
#line 158 "user.tmpl"
} // anon 
